# Generated by Django 4.2.23 on 2025-08-09 14:23

from django.db import migrations, connection


def drop_old_tables(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    cascade = " CASCADE" if vendor == "postgresql" else ""
    with schema_editor.connection.cursor() as cursor:
        # NOTE: do NOT drop jobapplier_application — it is used by the new
        # JobApplication model (db_table='jobapplier_application') created in 0003.
        cursor.execute(f"DROP TABLE IF EXISTS jobapplier_applicationstatushistory{cascade};")
        cursor.execute(f"DROP TABLE IF EXISTS jobapplier_userprofile{cascade};")


class Migration(migrations.Migration):

    dependencies = [
        ("jobapplier", "0004_add_verification_fields"),
    ]

    operations = [
        migrations.RunPython(drop_old_tables, migrations.RunPython.noop),
    ]
