# Generated by Django on 2025-08-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fyndr_auth", "0008_rename_company_name_recruiterprofile_resume_filename_and_more"),
        ("fyndr_auth", "0006_oauthtoken"),
    ]

    operations = [
        # OAuthToken was already created in 0006_oauthtoken; this migration is a no-op to resolve the merge conflict.
    ]
